version: '2.2'
services:
  vuln-server:
    build:
      context: .
      dockerfile: Dockerfile-vulnerable-server
    ports:
      - 127.0.0.1:5000:5000
  simple-http-server:
    build:
      context: .
      dockerfile: Dockerfile-http-simple-server
    ports:
      - 127.0.0.1:8000:8000
