FROM ubuntu:18.04

# Install things
RUN apt-get update -y && apt-get install python3-minimal python3-pip -y

# Create user
RUN useradd -ms /bin/bash app

### Copy app ###
RUN mkdir /web_app

# Install Python3 requirements
COPY requirements.txt /web_app/requirements.txt
RUN pip3 install -r /web_app/requirements.txt

COPY app /web_app/app
COPY config /web_app/config
COPY run_vulnerable_server.py /web_app/run_vulnerable_server.py
RUN chown app:app -R /web_app
WORKDIR /web_app




# Change user
USER app

CMD ["python3","-u", "run_vulnerable_server.py"]