version: '3'
services:
  nginx-waf:
    image: learnwebsec-nginx-modsec:v1
    #build:
    #  context: .
    #  dockerfile: docker/Dockerfile-nginx-modsec
    ports:
      - 127.0.0.1:80:80
    networks: 
      - default
      - backend
    depends_on:
      - vulnerable-app
  vulnerable-app:
    build:
      context: .
      dockerfile: docker/Dockerfile-app
    networks:
     - backend
  
  simple-http-server:
    build:
      context: .
      dockerfile: docker/Dockerfile-http-simple-server
    ports:
      - 127.0.0.1:8000:8000
    networks: 
      - default
    depends_on:
      - nginx-waf
  
networks: 
  backend: